version: '3'
services:
  redis:
    image: redis
    expose:
      - 6379
  
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}